version: '3.8'

services:
  frontend:
    image: ateulerlabs/ai-subtitler-frontend:${RELEASE_VERSION:-latest}
    ports:
      - "3000:3000"
    environment:
      - AI_BACKEND_URL=http://backend:5007
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ateulerlabs/ai-subtitler-backend:${RELEASE_VERSION:-latest}
    ports:
      - "5007:5007"
    volumes:
      - ./service-account-credentials/service-account.json:/app/credentials/service-account.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account.json
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 