version: '3.8'

services:
  frontend:
    image: ateulerlabs/ai-subtitler-frontend:${RELEASE_VERSION:-latest}
    ports:
      - "3000:3000"
    env_file:
      - ./frontend.env
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: ateulerlabs/ai-subtitler-backend:${RELEASE_VERSION:-latest}
    ports:
      - "5007:5007"
    volumes:
      - ./service-account-credentials/service-account.json:/app/credentials/service-account.json
    env_file:
      - ./backend.env
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge 